[workspace]
name = "pickup-tools"
channels = ["conda-forge"]
platforms = [
  {name = "osx-arm64-macos-12-0", platform = "osx-arm64", macos = "12.0"},
  {name = "osx-64-macos-12-0", platform = "osx-64", macos = "12.0"},
]

[dependencies]
python = "3.12.*"
git = "2.*"
