"""Install the pair using the provisioned Python, without invoking either skill."""

import argparse
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("bundle", type=Path)
    parser.add_argument("runtime", type=Path)
    parser.add_argument("--yes", action="store_true", help="Use default locations; never replace existing skills")
    parser.add_argument("--skills-dir", type=Path)
    parser.add_argument("--audit-dir", type=Path)
    args = parser.parse_args()
    skills = args.skills_dir or Path.home() / ".agents" / "skills"
    audit = args.audit_dir or Path(os.environ.get("PICKUP_HOME") or Path.home() / "Desktop" / "pickup_audit")
    print(f"Skills: {skills}\nAudit location: {audit}")
    if not args.yes:
        # A downloaded command may arrive on stdin; questions use the terminal.
        if not sys.stdin.isatty() and os.environ.get("PICKUP_STREAMED_INSTALL") == "1":
            sys.stdin = open("/dev/tty")
        if input("Use these locations? [Y/n] ").strip().lower() not in ("", "y", "yes"):
            skills = Path(input(f"Skills folder [{skills}]: ").strip() or skills)
            audit = Path(input(f"Audit folder [{audit}]: ").strip() or audit)
    skills, audit = skills.expanduser().resolve(), audit.expanduser().resolve()
    tools = args.runtime / "tools"
    binaries = args.runtime / ".pixi" / "envs" / "default" / "bin"
    python = binaries / "python3"
    for command in ([python, "-c", "import ctypes, hashlib, json; json.loads('{}')"],
                    [binaries / "git", "--version"], [tools / "gitleaks", "version"],
                    [tools / "gitleaks", "detect", "--help"],
                    [python, args.bundle / "treasurepickup" / "scripts" / "pickup_registry.py", "--help"]):
        subprocess.run(command, check=True, stdout=subprocess.DEVNULL)
    names = ("trashpickup", "treasurepickup")
    existing = [name for name in names if os.path.lexists(skills / name)]
    if existing and (args.yes or input("Replace existing Pickup skills, keeping a backup? [y/N] ").strip().lower() not in ("y", "yes")):
        raise ValueError("Existing Pickup skills were preserved.")
    skills.mkdir(parents=True, exist_ok=True)
    installed = []
    backup = None
    with tempfile.TemporaryDirectory(prefix=".pickup-install-", dir=skills) as temporary:
        stage = Path(temporary)
        for name in names:
            shutil.copytree(args.bundle / name, stage / name)
        config = stage / "treasurepickup" / "scripts" / "pickup-env.sh"
        config.write_text("\n".join([
            "# Generated by Pickup setup; applies only to the current command or shell.",
            "pickup_python=" + shlex.quote(str(python)),
            "pickup_git=" + shlex.quote(str(binaries / "git")),
            "pickup_gitleaks=" + shlex.quote(str(tools / "gitleaks")),
            "pickup_default_home=" + shlex.quote(str(audit)),
            'export PICKUP_HOME="${PICKUP_HOME:-$pickup_default_home}"',
            'export PYTHONDONTWRITEBYTECODE=1',
            'export PATH=' + shlex.quote(str(binaries) + ":" + str(tools)) + ':"$PATH"',
            "",
        ]))
        config.chmod(0o600)
        try:
            if existing:
                backup = Path(tempfile.mkdtemp(prefix=".pickup-backup-", dir=skills))
                for name in existing:
                    (skills / name).rename(backup / name)
            for name in names:
                if os.path.lexists(skills / name):
                    raise FileExistsError(f"Installation destination changed: {skills / name}")
                (stage / name).rename(skills / name)
                installed.append(skills / name)
        except BaseException:
            for path in installed:
                shutil.rmtree(path)
            if backup:
                for path in backup.iterdir():
                    path.rename(skills / path.name)
                backup.rmdir()
            raise
    print(f"Pickup installed: {skills}\nAudit location: {audit}")
    if backup:
        print(f"Previous skills retained: {backup}")
    print("Invoke /trashpickup to close a context. Supply its handoff and checkpoint with /treasurepickup in a fresh context.")


if __name__ == "__main__":
    try:
        main()
    except (EOFError, OSError, ValueError, subprocess.CalledProcessError) as error:
        raise SystemExit("Setup incomplete: " + str(error))
